- bin/cmake-js
- lib/cMake.js
- tests/cMakeTests.js
Some older compilers might not support c++11.
Adding an option to remove the CXX flag that forces it.
> Option to support old compilers

- README.md
- bin/cmake-js
- lib/buildSystem.js
A lot of projects can be used on multiple runtimes, e.g. between nw.js / electron. Also, most io.js / node.js projects can be used on nw.js / electron, so it doesn't fully make sense to have a project completely bound to a runtime.
I added the ability to over-ride runtime through command line arguments, which I think is absolutely essential for these reasons.
> Allow project runtime to be overriden

- bin/cmake-js
- lib/cMake.js
The commit adds command variable to create Xcode project with CMAKE, really useful while debugging addons on MAC 
cmake-js build -x 
cmake-js rebuild -x
> Ability to generate Xcode Project with make-js

- README.md
- bin/cmake-js
- lib/es6/cMake.js
- lib/es6/processHelpers.js
This PR adds a `silent` option to ignore the cMake's output on the stdio.
> Adds silent option to ignore cmake output

- README.md
- bin/cmake-js
- lib/es6/cMake.js
This PR adds an option to specify an output directory where to compile the program.
> Adds output directory option

- README.md
Technical Preview was superseded by final release: https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/ and the link in README no longer works.
> Fix the dead link to VC[++] Build Tools

- bin/cmake-js
- lib/es5/toolset.js
- lib/es6/toolset.js
Allow specification of generator from command line.
(Allows use of MinGW-64 instead of visual studio for instance) 
MUST complete; if a step fails when using this...
(MinGW Makefiles) cmake script complains if 'sh.exe' is in the path.  Normally I can just run ```cmake .``` again and finish the process... but cmake-js continues to error.
Second, I ended up doing it in an environment that was missing gcc, but didn't have sh.exe; so it finished with failure to find compilers, and retriggering failed.... 
But; deleting the build, having no sh.exe, having gcc in my path correctly - am able to finish building with 
cmake-js build -G "MinGW Makefiles" 
Error: could not find CMAKE_PROJECT_NAME in Cache
I guess; if it fails too soon that's the state.
> Add -G command line option to specify generator

- lib/es6/toolset.js
Using generator from new option leads to issue if SAFESEH needs to be set to NO.
> Fixing missing SAFESEH option if generator used from option

- lib/es6/cMake.js
I have Windows Server 2012 
node v7.5.0  (x64)
cmake 3.8.0-rc1  (x64)
build tools installed with 'npm install -g windows-build-tools'
The output received at line 73 in this windows platform has only \n in the buffer.
If you test for 'if stdout.includes('\r\n')' then you can handle it based on what was given, instead of assuming a platform is going to be a certain way.
This was causing 
ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio.
ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio.
I tracked it back to _getTopSupportedVisualStudioGenerator had a list that was empty ... [] ... 
and that's because of the parsing error.
> Test output instead of guessing by platform

- README.md
N-API is experimental at the moment, but for early adopters a short into may be useful.
> Add minimal documentation to use the new ABI-stable N-API (Node.js 8)

- lib/es6/dist.js
- lib/es6/downloader.js
- package.json
`tar` v1.x has a known vulnerability which was fixed in v2.
This fixes issue #68 
For testing, I've built my Electron app on Mac and Windows. I've also used the `npm test` suite. Building the prototype for `nw` actually failed for me, on both platforms. However it also failed on `master` with the same error, so probably not related to the `tar` changes?
The error had to do with the `v8::JSON::Parse` signature being incorrect, the files were still successfully extracted to `~/.cmake-js`.
> Update `tar` package

- README.md
- bin/cmake-js
- lib/es5/cMake.js
- lib/es5/toolset.js
- lib/es6/cMake.js
- lib/es6/toolset.js
Usage:
```bash
$ cmake-js build -T addon
```
Implements #91.
> Add -T option to specify target to build

- lib/es6/downloader.js
- package.json
unzipper is maintained fork of unzip
installing unzipper does not produce scary npm warnings
> replace unzip with unzipper

- lib/es6/cMake.js
This change "replace npmconf with rc (#119)"
```
let npmConfigData = require("rc")("npm");
```
in version 3.7.0 is breaking our builds , I fixed the code under node_modules and retested it on
npm version 5.7.1 looks good.
The variable was re-initialized to empty in the middle of the code and caused empty npmConfigData.
`npmConfigData = {}`
> remove incorrect initialization of npmConfigData to empty object

- lib/es5/cMake.js
- lib/es6/cMake.js
Otherwise, when attempting to specify a root output directory like
`--out ./build` build output will end up in `./build/build` for reasons
I don't fully understand. Using fully resolved paths is a good practice
in any case.
> Use a fully resolved path for `workDir`.

- lib/es6/toolset.js
This allows the underlying project to control compile-time
warnings instead of silencing them unconditionally.
See issue https://github.com/cmake-js/cmake-js/issues/132
> Remove disabling of warnings on OSX

- lib/es6/runtimePaths.js
Electron 4 changed the header directory to use the 'headerOnly' format rather than the 'full' node checkout format.
> :wrench: Support Electron v4

- README.md
I do not think that the hard-coded path to the folder is a good solution. Especially if it is a multi-package repository like [lerna](https://github.com/lerna/lerna)
> replacing hardcoded node-addon-api path with execute_command output

- lib/es6/toolset.js
The output of `cmake -E capabilities` has `Win64` suffix, so we need not add it manually. Closes #160.
```
{
"generators": [
{
"extraGenerators": [],
"name": "Visual Studio 15 2017 Win64",
"platformSupport": true,
"toolsetSupport": true
},
{
"extraGenerators": [],
"name": "Visual Studio 15 2017",
"platformSupport": true,
"toolsetSupport": true
},
{
"extraGenerators": [],
"name": "Visual Studio 15 2017 ARM",
"platformSupport": true,
"toolsetSupport": true
},
{
"extraGenerators": [],
"name": "Visual Studio 14 2015",
"platformSupport": true,
"toolsetSupport": true
},
{
"extraGenerators": [],
"name": "Visual Studio 12 2013 Win64",
"platformSupport": true,
"toolsetSupport": true
},
{
"extraGenerators": [],
"name": "Visual Studio 14 2015 Win64",
"platformSupport": true,
"toolsetSupport": true …
```
> Fix cmake generator

- lib/es6/toolset.js
Confirmed detection for fresh installs of:
- Build Tools 2019 via `choco install visualstudio2019-workload-vctools`
- VS 2019
- Build Tools 2017 via `choco install visualstudio2017-workload-vctools`
- NPM `windows-build-tools`
> Expand the vswhere.exe query to detect partial VS installations (#183)

- lib/es6/toolset.js
Catch the `The system cannot find the path specified.` error seen in #186 or other errors that arise from the vswhere process. VS installations without vswhere.exe should fall back to the previous workflow as intended.
> Handle installations with no vswhere.exe

- README.md
- bin/cmake-js
- changelog.md
- lib/cMake.js
- lib/toolset.js
The CMake Visual Studio 2019 Generator does not support the Win64 or ARM suffix on the generator name. Instead the generator platform must be set explicitly via the platform parameter.
Before this patch the platform was not set at all which results in CMake picking the host architecture. This obviously leads to mismatches if a 32bit NodeJS is used on a 64bit Windows.
Right now the platform parameter is only applied for Visual Studio 16 because cmake-js does not specify a minimum CMake version. If at least CMake 3.1 (released December 2014) would be required the platform selection code could be made unconditional and thus forward-compatible with newer CMake Visual Studio generators.
Thanks to @WopsS for #177 which added platform parameter support.
> Auto-detect Visual Studio 2019 platform

- lib/cMake.js
- lib/processHelpers.js
- lib/toolset.js
- lib/vsDetect.js
- tests/es6/testCases.js
Previously, cmake-js would fail if the cmake path contained spaces (See
issue #167). It would call exec() with a path that was not escaped or quoted,
and fail to run. If we fix that, then spawn fails for similar reasons. Update
both functions to just take the command line as an array of strings.
> Correctly handle spaces in paths

- lib/processHelpers.js
Fixes this issue:
https://github.com/cmake-js/cmake-js/issues/232
Solves the intent of this PR:
https://github.com/cmake-js/cmake-js/pull/225
The culprit is Microsoft - they decided they "wontfix"
https://github.com/dotnet/msbuild/issues/5726
Basically a default Windows 10 environment has a variable called Path (note the case). Some how in the node process this gets duped as PATH. Microsoft sees two path's in their environment and crashes.
> handle case when microsoft barfs on itself

- README.md
The Node.js core technology supporting the implementation on native add-ons previously known as **N-API** has been renamed to **Node-API** to make the name more appropriate and descriptive. This PR updates the project's documentation to reflect this change.
> Update documentation for Node-API

- lib/vsDetect.js
https://github.com/cmake-js/cmake-js/issues/249
Scanning through the docs for child_process -- https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback -- I can see that execFile includes a parameter controlling argument escaping, windowsVerbatimArguments, which default to false (and cmake-js does not override).  This lends some additional weight to the proposed fix to remove the manually-added quotes, as execFile should take care of it for us.
> Remove escaped quotes from windows registry queries

- README.md
- bin/cmake-js
- lib/cMake.js
Based on https://github.com/cmake-js/cmake-js/pull/216, which wasn't quite feature complete. I fixed the logic and added the build type configuration parameter to the options object so that a user can now specify custom CMAKE_BUILD_TYPE.
> Add config flag

- lib/toolset.js
cmake-js will only match "Visual Studio 16" for detecting platform, this PR change to getting the version of visual studio, and set platform according to the version.
Adding support for visual studio 2022 is the main purpose.
Open this new PR to avoid line ending issue.
> Auto-detect platform for Visual Studio 2019 and above

- lib/runtimePaths.js
On 05/06/2022, Electron changed the upload location of build artifacts. The former URL is not immediately obsolete, but will not reflect future updates. For example, Electron v19 build artifacts only exist in the new location now.
https://github.com/electron/electronjs.org/blob/2a2b89eca826710ed3d7b17d9b3e0a7534abfdc4/data/blog/s3-bucket-change.md
For example, currently, the following error occurred when trying to use v19.
```
info TOOL Using Unix Makefiles generator.
info DIST Downloading distribution files to: /Users/user/.cmake-js/electron-arm64/v19.0.3
http DIST       - https://atom.io/download/atom-shell/v19.0.3/node-v19.0.3.tar.gz
ERR! OMG Request failed with status code 403
ERR! OMG Request failed with status code 403
```
Missing version list generator: …
> Update baseurl for electron mirror

- lib/cpp/win_delay_load_hook.cc
The current `win_delay_load_hook.cc` does not account for situations where the host process is statically linked to node.exe but has been renamed.
When e.g. using `pkg` to create a single executable, any `.node` modules linked to `node.exe` will fail unless the final binary is also called `node.exe`.
This makes the hook more similar to that of node-gyp. See https://github.com/nodejs/node-gyp/blob/main/src/win_delay_load_hook.cc#L31
> fix: win_delay_load_hook.cc will fall back to the host process

- lib/cMake.js
Fix issue that causes this:
```
info CMD CONFIGURE
info RUN [
info RUN   'cmake',
info RUN   ...
info RUN   '-DCMAKE_JS_VERSION=undefined',
info RUN   ...
info RUN ]
```
Fixes https://github.com/cmake-js/cmake-js/issues/295
> fix: `-DCMAKE_JS_VERSION=undefined`

- bin/cmake-js
- lib/cMake.js
- tests/es6/buildSystem.js
- tests/es6/testCases.js
Partial duplicate of https://github.com/cmake-js/cmake-js/pull/235, except this PR:
* passes all `yargs`' unknown args to cmake (the ones after `--`)
* forwards args for all the basic commands (`clean`/`configure`/`build`)
* does _not_ forward args for composite commands (`compile`/`rebuild`/`reconfigure`)
Examples why this is nice:
```shell
npx cmake-js configure -- --debug-find-pkg=Foo --trace-source=FindFoo.cmake
npx cmake-js build -- -- CMakeFiles/my_lib.dir/my_src.cpp.o
npx cmake-js clean -- .cache /tmp/jest_rs
```
And can be paired with `--` in `package.json` npm scripts to forward args mostly* without extra `--`:
```shell
yarn cpp:clean .cache /tmp/jest_rs
npm run cpp:clean -- .cache /tmp/jest_rs
yarn cpp:configure --debug-find-pkg=Foo --trace-source=FindFoo.cmake
npm run …
```
> feat: Forward extra arguments to CMake commands

- lib/cMake.js
This PR only appends `CMAKE_BUILD_TYPE` to `CMAKE_LIBRARY_OUTPUT_DIRECTORY` if the build dir path doesn't already end with the build type.
Maintaining parallel build trees for release/debug can reduce rebuild times when switching between configs*.
If a user wishes to configure this way today, `cmake-js` defines a nonsense path for `LIBRARY_OUTPUT_DIRECTORY`:
```shell
npx cmake-js -D -O build/Debug
npx cmake-js -O build/Release
```
I assume this is to align with `node-gyp` and `require('bindings')('foo.node')`, which this PR would still support.
If the user configured into `build/${cmake_build_type}`, the `LIBRARY_OUTPUT_DIRECTORY` should be `${cmake_binary_dir}`, not `${cmake_binary_dir}/{cmake_build_type}`.
\* An alternative could be to customize the location of the object files based on …
> fix: Only add build type to `CMAKE_LIBRARY_OUTPUT_DIRECTORY` if needed

- lib/processHelpers.js
Bash on Windows defines both PATH and Path. This leads to a crash in MSBuild. Currently, `Path` is only removed from the environment, if it is the not the same as `PATH`. This commit changes this such, that `Path` is always removed, but if the two are not the same, it is appenden to `PATH`, too.
Closes #318
> always remove `Path` if `PATH` is also defined

- bin/cmake-js
Avoids automatic conversions from `yargs` by not using it for values that are supposed to be pass-through.
Fixes https://github.com/cmake-js/cmake-js/issues/313
> fix: Cmake arguments got converted to numbers

- README.md
Note that using `file(GLOB)` for defining the sources list is considered a bad practice in CMake https://cmake.org/cmake/help/v3.31/command/file.html#glob, we might want to change that to listing them explicitly rather than giving a bad sample
> Modernize CMakeLists.txt example
